# Z2API Deno优化版 - 独立部署配置
version: '3.8'

services:
  z2api-deno:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: z2api-deno
    ports:
      - "8081:8080"
    environment:
      # 基础配置
      - PORT=8080
      - DEFAULT_KEY=${DEFAULT_KEY:-123456}
      - UPSTREAM_URL=${UPSTREAM_URL:-https://chat.z.ai/api/chat/completions}
      - UPSTREAM_TOKEN=${UPSTREAM_TOKEN:-}
      
      # 性能配置
      - PERFORMANCE_MODE=${PERFORMANCE_MODE:-balanced}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - RETRY_DELAY=${RETRY_DELAY:-1000}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30000}
      - RANDOM_DELAY_MIN=${RANDOM_DELAY_MIN:-100}
      - RANDOM_DELAY_MAX=${RANDOM_DELAY_MAX:-500}
      
      # 功能配置
      - ANON_TOKEN_ENABLED=${ANON_TOKEN_ENABLED:-true}
      - THINK_TAGS_MODE=${THINK_TAGS_MODE:-think}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      
      # 日志配置
      - ENABLE_DETAILED_LOGGING=${ENABLE_DETAILED_LOGGING:-true}
      - LOG_USER_MESSAGES=${LOG_USER_MESSAGES:-false}
      - LOG_RESPONSE_CONTENT=${LOG_RESPONSE_CONTENT:-false}
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "deno", "eval", "fetch('http://localhost:8080/health').then(r => r.ok ? Deno.exit(0) : Deno.exit(1)).catch(() => Deno.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
